# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/md-irohas/geoipcli-go/
    steps:
      - checkout
      - run: go get -d -v
      - run: ./build.sh
      - store_artifacts:
          path: build/
      - persist_to_workspace:
          root: build/
          paths:
          - geoipcli-*

  deploy-to-github-release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - attach_workspace:
          at: /tmp/build/
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=v$(/tmp/build/geoipcli-go-linux-amd64 -version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/build/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy-to-github-release:
          requires:
            - build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
